import Vue from "vue";
//示例
import {
    PullRefresh,
    Card,
    Empty,
    List,
    Sidebar,
    SidebarItem,
    Button,
    Tabbar,
    TabbarItem,
    Checkbox,
    CheckboxGroup,
    Image as VanImage,
    Search,
    Lazyload,
    Tab,
    Tabs,
    Col,
    Row,
    Swipe,
    SwipeItem,
    Sticky,
    Grid,
    GridItem,
    Divider,
    Field,
    Cell,
    CellGroup,
    Overlay,
    NavBar,
    Icon,
    Sku,
    Tag,
    Stepper,
    SubmitBar,
    Toast,
    SwipeCell,
} from "vant";
Vue.use(NavBar);
Vue.use(PullRefresh);
Vue.use(SidebarItem);
Vue.use(Icon);
Vue.use(Sku);
Vue.use(Tag);
Vue.use(Stepper);
Vue.use(Toast);
Vue.use(Field);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Overlay);
Vue.use(Divider);
Vue.use(Empty);
Vue.use(List);
Vue.use(Sidebar);
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(VanImage);
Vue.use(Search);
Vue.use(Lazyload);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Col);
Vue.use(Row);
Vue.use(Sticky);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Card);
Vue.use(SubmitBar);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(SwipeCell);